controller_list:
  - name: fake_lower_body_controller
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_ee_group_controller
    joints:
      []
  - name: fake_lower_body_tcp2_controller
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6